services:
  keycloak:
    container_name: "keycloak-container"
    image: "muhohoweb/keycloak:1.0.2"
    command: [ "start-dev", "--http-relative-path=keycloak/auth" ]
    env_file:
      - keycloak/.env
    ports:
      - "8083:8080"
    depends_on:
      - postgres

  postgres:
    container_name: "postgres-container"
    image: "postgres:latest"
    platform: linux/amd64
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: "users_db"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  students-app:
    container_name: "students-container"
    build:
      context: .
      dockerfile: Dockerfile
    image: "muhohoweb/students-image:2.0.3"
    platform: linux/amd64
    restart: always
    ports:
      - "8081:8081"
    environment:
      COURSE_URL: "${COURSE_URL}"
      KEY_CLOAK_CLIENT_ID: "${KEY_CLOAK_CLIENT_ID}"
      KEY_CLOAK_USERNAME: "${KEY_CLOAK_USERNAME}"
      KEY_CLOAK_PASSWORD: "${KEY_CLOAK_PASSWORD}"


      DB_USER: "${DB_USER}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_URL: "jdbc:postgresql://postgres:5432/users_db"
      CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  cache:
  postgres-data:
  kafka-data:
#
