version: "3.8"

services:
  keycloak:
    container_name: "keycloak-container"
    image: quay.io/keycloak/keycloak:23.0.4
    command: [ "start-dev", "--http-relative-path=keycloak/auth" ]
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_HOSTNAME_ADMIN_URL: "http://localhost:8080/keycloak/auth/"
      KC_PROXY: "edge"
      KC_DB: "postgres"
      KC_DB_PASSWORD: "${DB_PASSWORD}"
      KC_DB_URL: "jdbc:postgresql://postgres:5432/school" # Call the postgres service
      KC_DB_USERNAME: "postgres"
      KC_HTTP_RELATIVE_PATH: "/auth"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: "postgres-container"
    image: "postgres:latest"
    platform: linux/amd64
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: "users_db"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  students-app:
    container_name: "students-container"
    build:
      context: .
      dockerfile: Dockerfile
    image: "muhohoweb/students-image:2.0.3"
    platform: linux/amd64
    restart: always
    ports:
      - "8081:8081"
    environment:
      COURSE_URL: "${COURSE_URL}"
      KEY_CLOAK_CLIENT_ID: "${KEY_CLOAK_CLIENT_ID}"
      KEY_CLOAK_USERNAME: "${KEY_CLOAK_USERNAME}"
      KEY_CLOAK_PASSWORD: "${KEY_CLOAK_PASSWORD}"


      DB_USER: "${DB_USER}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_URL: "jdbc:postgresql://postgres:5432/users_db"
      CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  cache:
  postgres-data:
  kafka-data:
#
