spring:
    profiles:
        active: "prod"
    application:
        name: users

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEY_CLOAK_ISSUER_URI}
                    jwk-set-uri: ${KEY_CLOAK_ISSUER_URI}/protocol/openid-connect/certs

    datasource:
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        username: ${DB_USERNAME}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                default_schema: students

server:
    port: 8081

# Actuator
management:
    health:
        circuitbreakers:
            enabled: true
    endpoints:
        web:
            exposure:
                include: health
    endpoint:
        health:
            show-details: always

# Resilience4j
resilience4j:
    circuitbreaker:
        instances:
            userService:
                register-health-indicator: true
                event-consumer-buffer-size: 10
                failure-rate-threshold: 50
                minimum-number-of-calls: 5
                automatic-transition-from-open-to-half-open-enabled: true
                wait-duration-in-open-state:
                    seconds: 5
                permitted-number-of-calls-in-half-open-state: 3
                sliding-window-size: 10
                sliding-window-type: COUNT_BASED

# CORS Configuration
cors:
    allowed:
        origins: ${CORS_ALLOWED_ORIGINS}
course:
    url: ${COURSE_URL}

jasypt:
    encryptor:
        password: hG7@eT!3rK9$yW0&  # The same secret key as in JasyptConfig
        algorithm: PBEWithMD5AndDES

aws:
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    region: us-east-1 # North Virginia
    sqs:
        queueUrl: https://sqs.us-east-1.amazonaws.com/975049979529/sqs_queue